// <auto-generated />
using DiscoverUO.Api.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscoverUO.Api.Migrations
{
    [DbContext(typeof(DiscoverUODatabaseContext))]
    [Migration("20241121032205_Init_Models")]
    partial class Init_Models
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DiscoverUO.Api.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PvPEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerBanner")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerEra")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerWebsite")
                        .HasColumnType("TEXT");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("DiscoverUO.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyVotesRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscoverUO.Api.Models.UserFavoritesList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("UserFavoritesLists");
                });

            modelBuilder.Entity("DiscoverUO.Api.Models.UserFavoritesListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FavoritesListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PvPEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerEra")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FavoritesListId");

                    b.ToTable("UserFavoritesListItems");
                });

            modelBuilder.Entity("DiscoverUO.Api.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAvatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserBiography")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDisplayName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("DiscoverUO.Api.Models.Server", b =>
                {
                    b.HasOne("DiscoverUO.Api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DiscoverUO.Api.Models.UserFavoritesList", b =>
                {
                    b.HasOne("DiscoverUO.Api.Models.User", "Owner")
                        .WithOne("Favorites")
                        .HasForeignKey("DiscoverUO.Api.Models.UserFavoritesList", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DiscoverUO.Api.Models.UserFavoritesListItem", b =>
                {
                    b.HasOne("DiscoverUO.Api.Models.UserFavoritesList", "FavoritesList")
                        .WithMany("FavoritedItems")
                        .HasForeignKey("FavoritesListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavoritesList");
                });

            modelBuilder.Entity("DiscoverUO.Api.Models.UserProfile", b =>
                {
                    b.HasOne("DiscoverUO.Api.Models.User", "Owner")
                        .WithOne("Profile")
                        .HasForeignKey("DiscoverUO.Api.Models.UserProfile", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DiscoverUO.Api.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("DiscoverUO.Api.Models.UserFavoritesList", b =>
                {
                    b.Navigation("FavoritedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
